---
- hosts: rpi
  remote_user: pi

  tasks:
  - name: install and update
    git:
      repo: https://github.com/spel-uchile/plantsat-payload-software.git
      dest: /home/pi/plantsat-payload-software
      force: yes

  - name: config flight software
    command:
      cmd: /bin/sh install.sh
      chdir: /home/pi/plantsat-payload-software
      creates: /home/pi/plantsat-payload-software/SUCHAI-Flight-Software/build_rpi/SUCHAI_Flight_Software

  - name: fix MCP I2C address
    replace:
      path: /home/pi/plantsat-payload-software/src/drivers/mcp9808/include/mcp9808.h
      regexp: 'MCP9808_I2CADDR_DEFAULT 0x1f'
      replace: 'MCP9808_I2CADDR_DEFAULT {{ mcp_i2c }}'
    when: mcp_i2c is defined


  - name: build plantsat payload software
    shell:
      cmd: mkdir -p build; cd build; cmake ..; make
      chdir: /home/pi/plantsat-payload-software
      warn: false

  - name: copy bin
    copy:
        src: /home/pi/plantsat-payload-software/build/PlantSat-Payload
        dest: /home/pi/bin/
        remote_src: yes
        mode: u+rwx

  - name: touch log files
    file:
      path: "/home/pi/bin/{{ item }}"
      state: touch
      mode: u+rw,g+rw,o+rw
    loop:
      - suchai-fs.out
      - suchai-fs.err

  - name: copy services file
    copy:
      src: "/home/pi/plantsat-payload-software/scripts/{{ item }}"
      dest: /home/pi/.local/share/systemd/user/
      remote_src: yes
    loop:
      - suchai-fs.service
      - zmq-hub.service

  - name: start suchai-fs service
    systemd:
      state: restarted
      daemon_reload: yes
      enabled: no
      scope: user
      name: "{{ item }}"
    loop:
      - suchai-fs
      - zmq-hub


